"""
Insurance image service.

Responsibilities:
- Accept one image per request.
- Verify that the invoice exists.
- Validate the actual image content.
- Allow JPEG images only.
- Generate the storage path on the backend.
- Save the image to disk.
- Create the corresponding database record.

The client must NOT provide the file path.
"""

from io import BytesIO
from pathlib import Path
from uuid import uuid4

from PIL import Image, UnidentifiedImageError
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models.insurance_image import (
    InsuranceImage,
    InsuranceImageType,
)
from app.models.insurance_invoice import InsuranceInvoice


# Change this later if you move image storage to another location.
IMAGE_STORAGE_ROOT = Path("data/uploads/insurance")

# Maximum accepted JPEG size: 10 MB.
MAX_IMAGE_SIZE = 10 * 1024 * 1024

# Reasonable protection against extremely large images.
MAX_IMAGE_WIDTH = 10000
MAX_IMAGE_HEIGHT = 10000


def create_insurance_image(
    db: Session,
    invoice_id: int,
    image_type: InsuranceImageType,
    image_bytes: bytes,
) -> InsuranceImage:
    """
    Validate and save one insurance image.

    The file path and filename are generated by the backend.

    Raises:
        ValueError:
            If the invoice does not exist.
            If image type is invalid.
            If image is empty.
            If image is too large.
            If image is not a valid JPEG.
            If image dimensions are unreasonable.
            If the image cannot be saved.
    """

    # ---------------------------------------------------------
    # 1. Verify invoice exists
    # ---------------------------------------------------------

    invoice = db.scalar(
        select(InsuranceInvoice).where(
            InsuranceInvoice.id == invoice_id
        )
    )

    if invoice is None:
        raise ValueError(
            "Insurance invoice does not exist."
        )

    # ---------------------------------------------------------
    # 2. Validate image type
    # ---------------------------------------------------------

    if not isinstance(
        image_type,
        InsuranceImageType,
    ):
        raise ValueError(
            "Invalid insurance image type."
        )

    # ---------------------------------------------------------
    # 3. Validate that image data exists
    # ---------------------------------------------------------

    if not image_bytes:
        raise ValueError(
            "Image data is required."
        )

    # ---------------------------------------------------------
    # 4. Validate file size
    # ---------------------------------------------------------

    if len(image_bytes) > MAX_IMAGE_SIZE:
        raise ValueError(
            "Image exceeds the maximum allowed size."
        )

    # ---------------------------------------------------------
    # 5. Validate actual image content
    # ---------------------------------------------------------

    try:
        with Image.open(BytesIO(image_bytes)) as image:

            # Verify actual image structure.
            image.verify()

        # Reopen because verify() invalidates the image object.
        with Image.open(BytesIO(image_bytes)) as image:

            # Do NOT trust the filename or Content-Type.
            if image.format != "JPEG":
                raise ValueError(
                    "Only JPEG images are allowed."
                )

            width, height = image.size

            if (
                width > MAX_IMAGE_WIDTH
                or height > MAX_IMAGE_HEIGHT
            ):
                raise ValueError(
                    "Image dimensions are too large."
                )

    except UnidentifiedImageError:
        raise ValueError(
            "Uploaded file is not a valid image."
        )

    # ---------------------------------------------------------
    # 6. Generate storage path
    # ---------------------------------------------------------

    invoice_directory = (
        IMAGE_STORAGE_ROOT
        / str(invoice_id)
        / image_type.value.lower()
    )

    invoice_directory.mkdir(
        parents=True,
        exist_ok=True,
    )

    filename = f"{uuid4().hex}.jpg"

    file_path = invoice_directory / filename

    # ---------------------------------------------------------
    # 7. Save image
    # ---------------------------------------------------------

    try:
        file_path.write_bytes(image_bytes)

    except OSError:
        raise ValueError(
            "Unable to save image."
        )

    # ---------------------------------------------------------
    # 8. Create database record
    # ---------------------------------------------------------

    image_record = InsuranceImage(
        invoice_id=invoice_id,
        image_type=image_type,
        file_path=str(file_path),
    )

    db.add(image_record)

    try:
        db.commit()
        db.refresh(image_record)

    except Exception:
        db.rollback()

        # Database failed after the file was written.
        # Remove the orphaned file.
        try:
            file_path.unlink(missing_ok=True)
        except OSError:
            pass

        raise

    return image_record